
		public enum Province {BRITISHCOLUMBIA, YUKON, ALBERTA, NORTHWESTTERRITORIES, SASKATCHEWAN, NUNAVUT, MANITOBA, ONTARIO, QUEBEC, NEWBRUNSWICK, NEWFOUNDLANDANDLABRADOR, PRINCEEDWARDISLAND, NOVASCOTIA}
